#!/usr/bin/env python

import socket, time

def encodeMessage(message):
    s = ""
    for k,v in message.iteritems():
        s += "%s: %s\n" % (k,v)
    return s

def sendMessage(message, host, port = 24441):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.sendto(encodeMessage(message), 0, (host, int(port)))
    (packet,address) = s.recvfrom(8192)
    return packet

message = {
    'PV': '2.0',
    'Thread': 123,
    'Op': 'shutdown',
    'User': 'anonymous',
    'Time': int(time.time()),
    'Sig': 'abc123'
 }

sendMessage(message, "127.0.0.1", 24441)

