#!/usr/bin/env python

import socket, time

def encodeMessage(message):
    s = ""
    for k,v in message.iteritems():
        s += "%s: %s\n" % (k,v)
    return s

def decodeMessage(message):
    m = {}
    for l in message.split("\n"):
        if len(l) != 0:
            k,v = l.split(": ")
            m[k] = v
    return m

def sendMessage(message, host, port = 24441):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.sendto(encodeMessage(message), 0, (host, int(port)))
    (packet,address) = s.recvfrom(8192)
    return decodeMessage(packet)

import sys

message = {
    'PV': '2.0',
    'Thread': int(time.time()),
    'Op': 'ping',
    'User': 'anonymous',
    'Time': int(time.time()),
    'Sig': 'abc123'
 }

if len(sys.argv) == 2:
    m = sendMessage(message, sys.argv[1])
else:
    m = sendMessage(message, '127.0.0.1')

if m['Code'] != "200":
    print "Server error: %s %s" % (m['Code'], m['Diag'])
else:
    for k,v in m.items():
        print "%s: %s" % (k,v)

